### PR TITLE
Some lil-fixes in docker-platform docs.

### PR DESCRIPTION
**Pull request by rezaxd**
Hello!
I'll get happy if there is another things that need to be done in docs of this platform.
I'll go for other asap.
Thx.

### CODE REVIEW

**Comment by rezaxd** [comment]
Hello @mhemrg .
As we talked, I reverted the prettier changes in docker deploy page.

**Comment by rezaxd** [comment]
Reminding! as u said @mhemrg .

**Comment by mhemrg** [comment]
Thanks for your contribution.
We have these kinds of writing issues on the other platforms, too. Are you interested in taking a look at those as well?
For example, we have the word "این‌طوری" in the NodeJS platform as well as Docker platform. Or there's room to improve the Disks section on all platforms.

**Comment by rezaxd** [comment]
@mhemrg Yeap, Sure!
Another thing that I want mention is using Prettier.
If u want, apply that on Docs. This would be great!

**Pull request closed without merging**
